#!/usr/bin/env python3
"""
Visual summary of the parser bugs with ASCII diagrams
"""

print("=" * 80)
print("SHOP INVENTORY PARSER BUG VISUALIZATION")
print("=" * 80)
print()

print("BUG #1: MISSING UNITS - BACKWARDS RANGE CALCULATION")
print("=" * 80)
print()

print("Save File Structure (shop m_portland_8671):")
print()
print("  Position  Section       Description")
print("  --------  -----------   ----------------------------------")
print("  51681     .spells       Contains spells for m_zcom_1308")
print("  51961     shop_id       m_zcom_1308")
print("  ...       ...           ...")
print("  56138     .shopunits    Contains units for m_portland_8671")
print("  56237     .temp         Metadata section")
print("  56420     shop_id       m_portland_8671")
print()

print("Parser Logic:")
print()
print("  1. Find .shopunits at 56138")
print("  2. Find .spells at 51681")
print("  3. Calculate: next_pos = spells_pos = 51681")
print("  4. Parse: data[56138:51681]  <- BACKWARDS RANGE!")
print()

print("Visual representation:")
print()
print("     51681              56138         56237  56420")
print("       |                  |             |      |")
print("       v                  v             v      v")
print("  [.spells]...........  [.shopunits][.temp][shop_id]")
print("       |                  |             |")
print("       |                  |             |")
print("       +------------------+             |")
print("           Backwards!                   |")
print("           Parser tries to              |")
print("           search from 56138            |")
print("           to 51681 = EMPTY             |")
print("                                        |")
print("       Correct range should be: --------+")
print("       From 56138 to 56237 (to .temp)")
print()

print("Result:")
print("  - data[56138:51681] = EMPTY (backwards)")
print("  - data.find(b\"strg\", 56138, 51681) = -1")
print("  - Parser returns [] (empty list)")
print("  - 4 units LOST: pirat, pirat2, bocman, sea_magess")
print()

print()
print("BUG #2: FALSE POSITIVE SPELLS - CROSS-SHOP SECTION ATTRIBUTION")
print("=" * 80)
print()

print("Parser searches backwards from shop ID to find sections:")
print()
print("  Shop m_portland_8671 at position 56420")
print("  Search backwards 5000 bytes: 56420 - 5000 = 51420")
print()

print("Visual representation:")
print()
print("  51420      51681        51961      55866      56420")
print("    |          |            |          |          |")
print("    v          v            v          v          v")
print("  [search  [.spells]    [m_zcom]  [m_port]   [m_port]")
print("   start]               [_1308]    [_6671]    [_8671]")
print("    |          |            |          |          |")
print("    |          +------------+----------+----------+")
print("    |             Parser finds this .spells for")
print("    |             ALL THREE shops!")
print("    |")
print("    +------------ Search range covers multiple shops")
print()

print("What happens:")
print("  1. Parser searches 5000 bytes backwards from m_portland_8671 (56420)")
print("  2. Finds .spells section at 51681")
print("  3. Assumes it belongs to m_portland_8671")
print("  4. But .spells actually belongs to m_zcom_1308 (at 51961)")
print()

print("Result:")
print("  - m_zcom_1308 shows 0 spells (should show 2)")
print("  - m_portland_6671 shows 2 spells (should show 0)")
print("  - m_portland_8671 shows 2 spells (should show 0)")
print("  - Same spells counted 2x in wrong shops!")
print()

print()
print("CORRECT APPROACH")
print("=" * 80)
print()

print("Fix #1: Only use sections AFTER current section")
print()
print("     51681              56138         56237  56420")
print("       |                  |             |      |")
print("       v                  v             v      v")
print("  [.spells]...........  [.shopunits][.temp][shop_id]")
print("                          |             |")
print("                          |             |")
print("                          +-------------+")
print("                          FORWARD RANGE")
print("                          From 56138 to 56237")
print()

print("Fix #2: Verify section ownership")
print()
print("  51681        51961      56138         56420")
print("    |            |          |             |")
print("    v            v          v             v")
print("  [.spells]  [m_zcom]  [.shopunits]  [m_port_8671]")
print("    |            |          |")
print("    |            |          |")
print("    +------------+          |")
print("    Belongs to              |")
print("    m_zcom_1308             |")
print("    (shop ID                |")
print("    between them)           |")
print("                            |")
print("                            +-> Belongs to m_portland_8671")
print("                                (no shop ID between)")
print()

print("Summary:")
print("  - Check for shop IDs between section and current shop")
print("  - If shop ID exists, section belongs to that shop, not us")
print("  - Only claim sections with clear ownership")
print()

