services:
  app:
    image: ghcr.io/sabnak/kbtracker:latest
    container_name: kbtracker_app
    environment:
      GAME_DATA_PATH: /data
      TZ: Europe/Moscow
    volumes:
      # Поменяйте пути! Часть после ":" остаётся неизменной.
      #
      # Путь к установленной игре. Если игр несколько, то каждый с новой строки!
      # Например: - 'C:/Games/Kings Bounty Darkside:/data/Darkside:ro'
      - '/path/to/your/game/Darkside:/data/Darkside:ro'
      #
      # Путь к сохранениям игр. Замените "C:/Users/<USERNAME>" на свой путь.
      - 'C:/Users/<USERNAME>/Documents/my games:/saves:ro'
    ports:
      - "9333:80"
    networks:
      - kbtracker-network
    restart: unless-stopped

networks:
  kbtracker-network:
    driver: bridge

volumes:
  postgres_data:
